In [20]:
import numpy as np
import matplotlib.pyplot as plt

In [21]:
A = np.matrix('1 -4 6; -7 4 3; 8 -0 -1')
B = np.matrix('3 1 -1; 2 8 5; -5 9 7')
C = np.matrix('5 -2 1; 10 -4 2; 15 -6 3')

In [22]:
# Matrix determinant
determinant_A = int(np.linalg.det(A))
determinant_B = int(np.linalg.det(B))
determinant_C = int(np.linalg.det(C))
print(determinant_A, determinant_B, determinant_C)

# Note that the determinant of matrix C is 0. This is a result of the columns of matrix C being linearly dependent, 
# which was deliberate.

-263 -64 0


In [23]:
# Eigenvalues and eigenvectors
eigenvalue_A, eigenvector_A = np.linalg.eig(A)
print(eigenvalue_A)
print(eigenvector_A)

eigenvalue_B, eigenvector_B = np.linalg.eig(B)
print(eigenvalue_B)
print(eigenvector_B)

eigenvalue_C, eigenvector_C = np.linalg.eig(C)
print(eigenvalue_C)
print(eigenvector_C)

[-8.57324357  9.24096332  3.33228024]
[[ 0.60084071  0.64554746  0.32983038]
 [ 0.48595099 -0.57355347  0.72128424]
 [-0.63469841  0.50428652  0.60906564]]
[-0.95404254  4.70932064 14.2447219 ]
[[-0.33032255  0.6363691  -0.01428194]
 [ 0.51534831  0.50249875  0.62216187]
 [-0.79076111 -0.58526009  0.78275835]]
[ 4.0000000e+00 -1.3766005e-16  1.7199892e-16]
[[ 0.26726124 -0.14644473 -0.34551944]
 [ 0.53452248  0.12456082 -0.92923959]
 [ 0.80178373  0.98134527 -0.13088197]]


In [34]:
# Check eigenvectors and eigenvalues are consistent
I = np.matrix('1 0 0; 0 1 0; 0 0 1')

result = []

for x in range(0, 3):
    result.append(int(np.linalg.det(A - (eigenvalue_A[x] * I))) == 0)
    result.append(int(np.linalg.det(B - (eigenvalue_B[x] * I))) == 0)
    result.append(int(np.linalg.det(C - (eigenvalue_C[x] * I))) == 0)

print(np.all(result))

True
