# Rotate matrix

## Problem statement

Given an image represented by an $N*N$ matrix, where each pixel in the image is represented by an integer, write a method to rotate the image by 90 degrees. Can you do this in place?

## Import packages

In [47]:
import numpy as np

## Solution 1

Create a new $N*N$ matrix and fill in the elements one-by-one.

Assume input is given as a standard Python list of lists.

In [48]:
def rotate_matrix_1(input, direction = 'clockwise'):
    
    # Check that input is square.
    if len(input) != len(input[0]): return 'ERROR: Input matrix is not square.'
    
    output = np.tile(0, (len(input), len(input)))
    
    for i in range(0, len(input)):
        for j in range(0, len(input)):
            if direction == 'clockwise':
                output[i][j] = input[len(input) - j - 1][i]
            else:
                output[i][j] = input[j][len(input) - i - 1]
    
    return output

#### Test cases

In [49]:
print(1, rotate_matrix_1([[1, 2, 3], [4, 5, 6]]))
print(2, rotate_matrix_1([[1, 2], [3, 4]], 'clockwise'))
print(3, rotate_matrix_1([[1, 2], [3, 4]], 'anti-clockwise'))
print(4, rotate_matrix_1([[1, 2, 3], [4, 5, 6], [7, 8, 9]], 'clockwise'))
print(5, rotate_matrix_1([[1, 2, 3], [4, 5, 6], [7, 8, 9]], 'anti-clockwise'))

1 ERROR: Input matrix is not square.
2 [[3 1]
 [4 2]]
3 [[2 4]
 [1 3]]
4 [[7 4 1]
 [8 5 2]
 [9 6 3]]
5 [[3 6 9]
 [2 5 8]
 [1 4 7]]
