# Zero matrix

## Problem statement

Write an algorithm such that if an element in an $M*M$ matrix is 0, its entire row and column are set to 0.

## Import packages

In [7]:
import numpy as np

## Solution 1

Assume the input is given as a list of lists. Iterate through each element in the matrix and, if it is zero, set the row and column of that element to zero.

This is a brute force method that involves a lot of duplicated work and no optimisation. Time complexity: $O(N^2)$

In [48]:
def zero_matrix_1(input_mat):
    'Sets the column and row of any matrix element with 0 to 0.'
    
    if len(input_mat) != len(input_mat[0]): return 'ERROR: Input is not a square matrix.'
    
    input_mat = np.matrix(input_mat)
    output_mat = np.matrix(input_mat)
    
    for i in range(len(output_mat)):
        for j in range(len(output_mat)):
            if input_mat[i, j] == 0:
                output_mat[i, :] = 0
                output_mat[:, j] = 0
    
    return output_mat

#### Test cases

In [52]:
print(zero_matrix_1([[1, 2, 3], [4, 5, 6]]))
print(zero_matrix_1([[1, 3], [3, 0]]))
print(zero_matrix_1([[1, 2, 3], [4, 5, 6], [7, 0, 9]]))
print(zero_matrix_1([[1, 2], [3, 4]]))
print(zero_matrix_1([[1, 0, 3, 4], [5, 6, 7, 8], [9, 10, 0, 12], [13, 14, 15, 16]]))

ERROR: Input is not a square matrix.
[[1 0]
 [0 0]]
[[1 0 3]
 [4 0 6]
 [0 0 0]]
[[1 2]
 [3 4]]
[[ 0  0  0  0]
 [ 5  0  0  8]
 [ 0  0  0  0]
 [13  0  0 16]]


## Solution 2

Assume the input is given as a list of lists. Iterate through each row. If a row contains a zero, set that row equal to zero. Repeat this for columns.

Time complexity: $O(N)$

In [57]:
def zero_matrix_2(input_mat):
    'Sets the column and row of any matrix element with 0 to 0.'
    
    if len(input_mat) != len(input_mat[0]): return 'ERROR: Input is not a square matrix.'
    
    input_mat = np.matrix(input_mat)
    output_mat = np.matrix(input_mat)
    
    for i in range(len(output_mat)):
        if 0 in input_mat[i, :]:
            output_mat[i, :] = 0
    
    for j in range(len(output_mat)):
        if 0 in input_mat[:, j]:
            output_mat[:, j] = 0
    
    return output_mat

#### Test cases

In [58]:
print(zero_matrix_2([[1, 2, 3], [4, 5, 6]]))
print(zero_matrix_2([[1, 3], [3, 0]]))
print(zero_matrix_2([[1, 2, 3], [4, 5, 6], [7, 0, 9]]))
print(zero_matrix_2([[1, 2], [3, 4]]))
print(zero_matrix_2([[1, 0, 3, 4], [5, 6, 7, 8], [9, 10, 0, 12], [13, 14, 15, 16]]))

ERROR: Input is not a square matrix.
[[1 0]
 [0 0]]
[[1 0 3]
 [4 0 6]
 [0 0 0]]
[[1 2]
 [3 4]]
[[ 0  0  0  0]
 [ 5  0  0  8]
 [ 0  0  0  0]
 [13  0  0 16]]
